version: '3'
services:
  frontend:
    stdin_open: true
    tty: true
    image: download-media-image
    container_name: frontend-download-media
    build:
      context: .
    ports:
      - '3000:3000'
